// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWdhxbCUKgf7FQrZgOSH5qPB_RQ-LXrkk',
    appId: '1:687889462248:web:7120648d92ee2661dd2a5d',
    messagingSenderId: '687889462248',
    projectId: 'universityrideshare-6cb8e',
    authDomain: 'universityrideshare-6cb8e.firebaseapp.com',
    storageBucket: 'universityrideshare-6cb8e.firebasestorage.app',
    measurementId: 'G-XQ4VZ8ZGKJ',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZERxIV51z3N10J83f-H0cDmN-ZaoPvKU',
    appId: '1:687889462248:android:86c61dfad7ed0f75dd2a5d',
    messagingSenderId: '687889462248',
    projectId: 'universityrideshare-6cb8e',
    storageBucket: 'universityrideshare-6cb8e.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_eim0NHj_HcxDEvuJbWcj3fEvVwHJ7Q',
    appId: '1:687889462248:ios:6e355940ff2eddeadd2a5d',
    messagingSenderId: '687889462248',
    projectId: 'universityrideshare-6cb8e',
    storageBucket: 'universityrideshare-6cb8e.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_eim0NHj_HcxDEvuJbWcj3fEvVwHJ7Q',
    appId: '1:687889462248:ios:6e355940ff2eddeadd2a5d',
    messagingSenderId: '687889462248',
    projectId: 'universityrideshare-6cb8e',
    storageBucket: 'universityrideshare-6cb8e.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWdhxbCUKgf7FQrZgOSH5qPB_RQ-LXrkk',
    appId: '1:687889462248:web:cc070d6c8dc4ec12dd2a5d',
    messagingSenderId: '687889462248',
    projectId: 'universityrideshare-6cb8e',
    authDomain: 'universityrideshare-6cb8e.firebaseapp.com',
    storageBucket: 'universityrideshare-6cb8e.firebasestorage.app',
    measurementId: 'G-Q6ED496CBW',
  );
}
